### ISSUE TITLE
Compiling `VideoPipe.c` fails with type errors on Pi 4

### ISSUE THREAD

**Issue by Jamie-** [adrianseeley/FastMJPG#3]
I'm building on Raspbian 11 Bullseye on a Pi 4, following the instructions in the README. Compiliation of `VideoPipe.c` fails with the following errors:
```
$ ./build 
gcc -Wall -Wextra -Werror -O3 -I./include -c ./src/GLAD.c -o ./obj/GLAD.o
gcc -Wall -Wextra -Werror -O3 -I./include -c ./src/VideoCapture.c -o ./obj/VideoCapture.o
gcc -Wall -Wextra -Werror -O3 -I./include -c ./src/VideoDecoder.c -o ./obj/VideoDecoder.o
gcc -Wall -Wextra -Werror -O3 -I./include -c ./src/VideoPipe.c -o ./obj/VideoPipe.o
./src/VideoPipe.c: In function ‘VideoPipeWriteFrame’:
./src/VideoPipe.c:25:67: error: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘ssize_t’ {aka ‘int’} [-Werror=format=]
   25 |         fprintf(stderr, "Error writing timestamp to pipe. Wrote %ld bytes instead of %ld bytes.\n", bytesWritten, sizeof(uint64_t));
      |                                                                 ~~^                                 ~~~~~~~~~~~~
      |                                                                   |                                 |
      |                                                                   long int                          ssize_t {aka int}
      |                                                                 %d
./src/VideoPipe.c:25:88: error: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘unsigned int’ [-Werror=format=]
   25 |         fprintf(stderr, "Error writing timestamp to pipe. Wrote %ld bytes instead of %ld bytes.\n", bytesWritten, sizeof(uint64_t));
      |                                                                                      ~~^                          ~~~~~~~~~~~~~~~~
      |                                                                                        |                          |
      |                                                                                        long int                   unsigned int
      |                                                                                      %d
./src/VideoPipe.c:35:64: error: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘ssize_t’ {aka ‘int’} [-Werror=format=]
   35 |         fprintf(stderr, "Error writing length to pipe. Wrote %ld bytes instead of %ld bytes.\n", bytesWritten, sizeof(uint32_t));
      |                                                              ~~^                                 ~~~~~~~~~~~~
      |                                                                |                                 |
      |                                                                long int                          ssize_t {aka int}
      |                                                              %d
./src/VideoPipe.c:35:85: error: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘unsigned int’ [-Werror=format=]
   35 |         fprintf(stderr, "Error writing length to pipe. Wrote %ld bytes instead of %ld bytes.\n", bytesWritten, sizeof(uint32_t));
      |                                                                                   ~~^                          ~~~~~~~~~~~~~~~~
      |                                                                                     |                          |
      |                                                                                     long int                   unsigned int
      |                                                                                   %d
./src/VideoPipe.c:46:26: error: comparison of integer expressions of different signedness: ‘ssize_t’ {aka ‘int’} and ‘uint32_t’ {aka ‘unsigned int’} [-Werror=sign-compare]
   46 |         if (bytesWritten != bytesToWrite) {
      |                          ^~
./src/VideoPipe.c:47:67: error: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘ssize_t’ {aka ‘int’} [-Werror=format=]
   47 |             fprintf(stderr, "Error writing frame to pipe. Wrote %ld bytes instead of %u bytes.\n", bytesWritten, bytesToWrite);
      |                                                                 ~~^                                ~~~~~~~~~~~~
      |                                                                   |                                |
      |                                                                   long int                         ssize_t {aka int}
      |                                                                 %d
cc1: all warnings being treated as errors
Compilation failed for !
```

Using gcc version: `gcc version 10.2.1 20210110 (Raspbian 10.2.1-6+rpi1)`

**Comment by Jamie-** [comment]
I think those errors might be specific to building on a Pi (ARM vs x64 maybe?) as this doesn't appear on Intel also running Debian 11 Bullseye (but that then later fails as detailed in #4).

Modifying the build script on the Pi to remove `-Wall -Wextra -Werror` allows the build to proceed, and then that also fails in the same way as in #4.

**Comment by Macrobiotic** [comment]
I've got stuck in the same way under Raspberry Pi OS. I'm trying with Ubuntu for ARM on the Pi, to see if that works better.

**Comment by adrianseeley** [comment]
Ah yes I see the issue, on x64 ssize and size are actually longs but on arm they are just regular ints, should have a new build shortly for this, thanks for reporting!

**Comment by adrianseeley** [comment]
This should be fixed now: https://github.com/adrianseeley/FastMJPG/commit/1fce459f362338dfb1eb906a3bc7eb13eb38781d

These were some old debug print statements that don't actually need to echo the values any longer as that behavior has been confirmed working already. I'll leave the issue open so @Macrobiotic or @Jamie- can confirm it is indeed working as expected now on those devices.

**Comment by Jamie-** [comment]
Hey, thanks for pushing a fix. Just git pulled and tried to rebuild, all the errors from the print statements are gone :+1: however the `if` comparison error still fails the build.

```
$ ./build 
gcc -Wall -Wextra -Werror -O3 -I./include -c ./src/GLAD.c -o ./obj/GLAD.o
gcc -Wall -Wextra -Werror -O3 -I./include -c ./src/VideoCapture.c -o ./obj/VideoCapture.o
gcc -Wall -Wextra -Werror -O3 -I./include -c ./src/VideoDecoder.c -o ./obj/VideoDecoder.o
gcc -Wall -Wextra -Werror -O3 -I./include -c ./src/VideoPipe.c -o ./obj/VideoPipe.o
./src/VideoPipe.c: In function ‘VideoPipeWriteFrame’:
./src/VideoPipe.c:46:26: error: comparison of integer expressions of different signedness: ‘ssize_t’ {aka ‘int’} and ‘uint32_t’ {aka ‘unsigned int’} [-Werror=sign-compare]
   46 |         if (bytesWritten != bytesToWrite) {
      |                          ^~
cc1: all warnings being treated as errors
Compilation failed for !
```

**Comment by adrianseeley** [comment]
https://github.com/adrianseeley/FastMJPG/commit/d6c9df99a283f308e49dade2388c4e4c2abf4a21 That should do it there, if you can confirm (on master).
